package tuf.webscaf.app.dbContext.slave.repositry;

import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import tuf.webscaf.app.dbContext.slave.entity.SlaveStudentGuardianFinancialHistoryEntity;

import java.util.UUID;

@Repository
public interface SlaveStudentGuardianFinancialHistoryRepository extends ReactiveCrudRepository<SlaveStudentGuardianFinancialHistoryEntity, Long> {

    Mono<SlaveStudentGuardianFinancialHistoryEntity> findByUuidAndDeletedAtIsNull(UUID uuid);

    Flux<SlaveStudentGuardianFinancialHistoryEntity> findAllByAssetNameContainingIgnoreCaseAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndDeletedAtIsNull(Pageable pageable, String assetName, String description);

    Flux<SlaveStudentGuardianFinancialHistoryEntity> findAllByAssetNameContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStatusAndDeletedAtIsNull(Pageable pageable, String assetName,Boolean status1, String description,Boolean status2);

    Flux<SlaveStudentGuardianFinancialHistoryEntity> findAllByAssetNameContainingIgnoreCaseAndStudentGuardianUUIDAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStudentGuardianUUIDAndDeletedAtIsNull(Pageable pageable, String assetName,UUID studentGuardianUUID, String description,UUID studentGuardianUUID2);

    Flux<SlaveStudentGuardianFinancialHistoryEntity> findAllByAssetNameContainingIgnoreCaseAndStudentGuardianUUIDAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStudentGuardianUUIDAndStatusAndDeletedAtIsNull(Pageable pageable, String assetName,UUID studentGuardianUUID, Boolean status, String description,UUID studentGuardianUUID2, Boolean status2);

    Mono<Long> countByAssetNameContainingIgnoreCaseAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndDeletedAtIsNull(String assetName,String description);

    Mono<Long> countByAssetNameContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStatusAndDeletedAtIsNull(String assetName,Boolean status1,String description,Boolean status2);

    Mono<Long> countByAssetNameContainingIgnoreCaseAndStudentGuardianUUIDAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStudentGuardianUUIDAndDeletedAtIsNull(String assetName,UUID studentGuardianUUID, String description,UUID studentGuardianUUID2);

    Mono<Long> countByAssetNameContainingIgnoreCaseAndStudentGuardianUUIDAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStudentGuardianUUIDAndStatusAndDeletedAtIsNull(String assetName,UUID studentGuardianUUID, Boolean status, String description,UUID studentGuardianUUID2, Boolean status2);

    Mono<SlaveStudentGuardianFinancialHistoryEntity> findByIdAndDeletedAtIsNull(Long id);

    //Find By Currency uuid In Config Module
    Mono<SlaveStudentGuardianFinancialHistoryEntity> findFirstByCurrencyUUIDAndDeletedAtIsNull(UUID currencyUUID);
}
