package tuf.webscaf.app.dbContext.slave.repositry;

import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import tuf.webscaf.app.dbContext.slave.entity.SlaveTeacherSpouseFamilyDoctorEntity;

import java.util.UUID;

@Repository
public interface SlaveTeacherSpouseFamilyDoctorRepository extends ReactiveCrudRepository<SlaveTeacherSpouseFamilyDoctorEntity, Long> {
    Flux<SlaveTeacherSpouseFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndDeletedAtIsNull(Pageable pageable, String name, String description, String clinicalAddress);

    Flux<SlaveTeacherSpouseFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndStatusAndDeletedAtIsNull(Pageable pageable, String name, Boolean status1, String description, Boolean status2, String clinicalAddress, Boolean status3);

    Flux<SlaveTeacherSpouseFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndTeacherSpouseUUIDAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherSpouseUUIDAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherSpouseUUIDAndDeletedAtIsNull(Pageable pageable, String name, UUID teacherSpouseUUID, String description, UUID teacherSpouseUUID2, String clinicalAddress, UUID teacherSpouseUUID3);

    Flux<SlaveTeacherSpouseFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndTeacherSpouseUUIDAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherSpouseUUIDAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherSpouseUUIDAndStatusAndDeletedAtIsNull(Pageable pageable, String name, UUID teacherSpouseUUID, Boolean status, String description, UUID teacherSpouseUUID2, Boolean status2, String clinicalAddress, UUID teacherSpouseUUID3, Boolean status3);

    Mono<Long> countByNameContainingIgnoreCaseAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndDeletedAtIsNull(String name, String description, String clinicalAddress);

    Mono<Long> countByNameContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndStatusAndDeletedAtIsNull(String name, Boolean status1, String description, Boolean status2, String clinicalAddress, Boolean status3);

    Mono<Long> countByNameContainingIgnoreCaseAndTeacherSpouseUUIDAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherSpouseUUIDAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherSpouseUUIDAndDeletedAtIsNull(String name, UUID teacherSpouseUUID, String description, UUID teacherSpouseUUID2, String clinicalAddress, UUID teacherSpouseUUID3);

    Mono<Long> countByNameContainingIgnoreCaseAndTeacherSpouseUUIDAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherSpouseUUIDAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherSpouseUUIDAndStatusAndDeletedAtIsNull(String name, UUID teacherSpouseUUID, Boolean status, String description, UUID teacherSpouseUUID2, Boolean status2, String clinicalAddress, UUID teacherSpouseUUID3, Boolean status3);

    Mono<SlaveTeacherSpouseFamilyDoctorEntity> findByIdAndDeletedAtIsNull(Long id);

    Mono<SlaveTeacherSpouseFamilyDoctorEntity> findByUuidAndDeletedAtIsNull(UUID uuid);

}
