package tuf.webscaf.app.dbContext.slave.repositry;

import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.reactive.ReactiveCrudRepository;
import org.springframework.stereotype.Repository;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import tuf.webscaf.app.dbContext.slave.entity.SlaveTeacherChildFamilyDoctorEntity;

import java.util.UUID;

@Repository
public interface SlaveTeacherChildFamilyDoctorRepository extends ReactiveCrudRepository<SlaveTeacherChildFamilyDoctorEntity, Long> {
    Flux<SlaveTeacherChildFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndDeletedAtIsNull(Pageable pageable, String name, String description, String clinicalAddress);

    Flux<SlaveTeacherChildFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndStatusAndDeletedAtIsNull(Pageable pageable, String name, Boolean status1, String description, Boolean status2, String clinicalAddress, Boolean status3);

    Flux<SlaveTeacherChildFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndTeacherChildUUIDAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherChildUUIDAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherChildUUIDAndDeletedAtIsNull(Pageable pageable, String name, UUID teacherChildUUID, String description, UUID teacherChildUUID2, String clinicalAddress, UUID teacherChildUUID3);

    Flux<SlaveTeacherChildFamilyDoctorEntity> findAllByNameContainingIgnoreCaseAndTeacherChildUUIDAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherChildUUIDAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherChildUUIDAndStatusAndDeletedAtIsNull(Pageable pageable, String name, UUID teacherChildUUID, Boolean status, String description, UUID teacherChildUUID2, Boolean status2, String clinicalAddress, UUID teacherChildUUID3, Boolean status3);

    Mono<Long> countByNameContainingIgnoreCaseAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndDeletedAtIsNull(String name, String description, String clinicalAddress);

    Mono<Long> countByNameContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndStatusAndDeletedAtIsNull(String name, Boolean status1, String description, Boolean status2, String clinicalAddress, Boolean status3);

    Mono<Long> countByNameContainingIgnoreCaseAndTeacherChildUUIDAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherChildUUIDAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherChildUUIDAndDeletedAtIsNull(String name, UUID teacherChildUUID, String description, UUID teacherChildUUID2, String clinicalAddress, UUID teacherChildUUID3);

    Mono<Long> countByNameContainingIgnoreCaseAndTeacherChildUUIDAndStatusAndDeletedAtIsNullOrDescriptionContainingIgnoreCaseAndTeacherChildUUIDAndStatusAndDeletedAtIsNullOrClinicalAddressContainingIgnoreCaseAndTeacherChildUUIDAndStatusAndDeletedAtIsNull(String name, UUID teacherChildUUID, Boolean status, String description, UUID teacherChildUUID2, Boolean status2, String clinicalAddress, UUID teacherChildUUID3, Boolean status3);

    Mono<SlaveTeacherChildFamilyDoctorEntity> findByIdAndDeletedAtIsNull(Long id);

    Mono<SlaveTeacherChildFamilyDoctorEntity> findByUuidAndDeletedAtIsNull(UUID uuid);

}
